args <- commandArgs(trailingOnly=FALSE)
script <- sub("^--file=","",args[grepl("^--file=",args)][1])
setwd(dirname(normalizePath(script)))
source('app.R')
shiny::testServer(server, {
 session$setInputs(mode='demo',nodes='all',window='10',endpoint='http://127.0.0.1:8000')
 stopifnot(nrow(filtered())>2000,nrow(summaries())==4)
 exported <- read.csv(output$download)
 stopifnot(nrow(exported)>2000,all(exported$data_source=='SIMULATED'))
 stopifnot(grepl('SIMULATED',as.character(output$mode_banner$html)))
 session$setInputs(mode='live',endpoint='http://127.0.0.1:1')
 stopifnot(nrow(filtered())==0,!is.null(source_data()$error))
})
cat('Shiny server state tests passed\n')
