args <- commandArgs(trailingOnly=FALSE)
script <- sub("^--file=","",args[grepl("^--file=",args)][1])
setwd(dirname(normalizePath(script)))
source("analytics.R")
d <- make_demo(as.POSIXct("2026-09-22 12:00:00",tz="UTC"))
stopifnot(nrow(d)>2000,nrow(node_summary(d,as.POSIXct("2026-09-22 12:00:00",tz="UTC")))==4)
x <- d[1:3,]; x$node_id <- 'a'; x$boot_id <- 'b'; x$sequence <- c(0,1,4)
v <- span_delivery(x); stopifnot(v$received==3,v$expected==5,v$missing==2,v$pct==60)
x$boot_id[3] <- 'c'; x$sequence[3] <- 0
stopifnot(span_delivery(x)$missing==0)
x <- rbind(x,x[1,]); x$received_at <- format(x$received_at,"%Y-%m-%dT%H:%M:%OS3Z",tz="UTC")
stopifnot(nrow(prepare_data(x))==3,nrow(range_summary(d))==16)
stopifnot(sum(node_summary(d,as.POSIXct("2026-09-22 12:00:00",tz="UTC"))$state=='OFFLINE')==1)
cat("R analytics tests passed\n")
